# http://docs.haskellstack.org/en/stable/travis_ci.html
sudo: false

language: haskell

branches:
    only:
        - master

addons:
    apt:
        sources:
            - mongodb-3.2-precise
        packages:
            - libssh2-1-dev

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack setup
    - stack install --dependencies-only

script:
    - stack build
